services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
  web:
    image: node:lts
<<<<<<< HEAD
    user: 'root'
=======
    user: 'node'
>>>>>>> fb3bff6 (Maybe docker works this time)
    working_dir: /ProjectSourceCode
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/ProjectSourceCode
<<<<<<< HEAD
    command: 
      # for testing
      'npm run testandrun'

      # for functionality
      # 'npm start'
=======
    command: 'npm start'
>>>>>>> fb3bff6 (Maybe docker works this time)
volumes:
  group-project: